# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JWAlertController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JWAlertController
  pod 'Masonry'

  target 'JWAlertControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JWAlertControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
