# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iCarouselDemo' do

  # Pods for iCarouselDemo
	pod 'iCarousel'
    pod 'Masonry'

  target 'iCarouselDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iCarouselDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
