# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ViewControllerProgrammingGuideDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ViewControllerProgrammingGuideDemo
  pod 'Masonry'
  target 'ViewControllerProgrammingGuideDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
